---
- name: pipelining対応用play
  hosts: all
  become: yes
  vars:
    ansible_ssh_pipelining: no
  tasks:
    - name: ansible_userに対するrequiretty設置を無効化
      lineinfile:
        dest: /etc/sudoers
        regexp: '^Defaults:{{ ansible_user }}\srequiretty'
        line: 'Defaults:{{ ansible_user }} requiretty '
        validate: 'visudo -cd %s'
        backup: yes

- name: CentOS7上にWordPressをセットアップする
  hosts: all
  become: true
  vars:
    db_name: wordpress
    db_user: wordpress
    db_password: myQ1InsecureP@ssW0rd
  roles:
    - name: common
      tags:
        - common

    - name: mariadb
      vars:
        mariadb_databases:
          - name: "{{ db_name }}"
        mariadb_users:
          - name: "{{ db_user }}"
            password: "{{ db_password }}"
            priv: "{{ db_name }}.*:ALL"
      tags:
        - mariadb

    - name: php-fpm
      vars:
        php_fpm_additional_package:
          - php-mysqlnd
      tags:
        - php-fpm

    - name: nginx
      tags:
        - nginx

    - name: wordpress
      tags:
        wordpress
